import { NextRequest, NextResponse } from "next/server";
import { resolveUserFromSession } from "@/lib/session-utils";
import { SCRIPT_REVIEW_PROMPT, SCRIPT_REVIEW_CHAT_SYSTEM_PROMPT } from "@/lib/audit-engine";
import Anthropic from "@anthropic-ai/sdk";
import prisma from "@/lib/prisma";

const claude = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// Change 1: Fixed invalid model string — was "claude-sonnet-4-20250514" (non-existent)
const MODEL = "claude-3-5-sonnet-latest";

async function getSystemPromptForMode(userId: string, mode: "analysis" | "chat", avatar: string): Promise<string> {
  const key = mode === "analysis" ? "script_review_analysis_prompt" : "script_review_chat_prompt";
  const defaultPrompt = mode === "analysis" ? SCRIPT_REVIEW_PROMPT : SCRIPT_REVIEW_CHAT_SYSTEM_PROMPT;

  const setting = await prisma.appSetting.findUnique({ where: { key } });
  const prompt = setting?.value ?? defaultPrompt;
  return prompt.replace("{{AVATAR_CONTEXT}}", avatar);
}

// Change 4: Updated buildAvatarContext to inject the full 11-section avatarProfile document
// including anxiety phases, internal monologue, emotional triggers, fears, and creator credentials.
// Previously only pulled avatarName, avatarSummary, and contentThemes (surface-level fields).
// Merged with remote improvements to content theme detail rendering.
function buildAvatarContext(user: any): { block: string; name: string | null } {
  const hasAnyAvatarData =
    user.avatarSummary ||
    user.avatarName ||
    user.avatarProfile ||
    user.creatorCredentials;

  if (!hasAnyAvatarData) {
    return {
      block: "",
      name: null,
    };
  }

  let block = "=== MEMBER AVATAR — HARD CONSTRAINT ===\n";
  block += "This is who the script must speak to. Every tone decision, word choice, and emotional beat must be calibrated to this specific person.\n\n";

  if (user.avatarName) block += `Avatar Name: ${user.avatarName}\n`;
  if (user.avatarSummary) block += `Avatar Summary: ${user.avatarSummary}\n\n`;

  // Inject the full avatarProfile document (generated by the Avatar Architect).
  // This contains all 11 sections: life stage, income, fears, anxiety phases,
  // internal monologue, emotional triggers, values, content themes, etc.
  if (user.avatarProfile) {
    const profile = user.avatarProfile as any;
    if (profile.full_document) {
      // Prefer the pre-rendered full document if available
      block += `Full Avatar Document:\n${profile.full_document}\n\n`;
    } else {
      // Fall back to structured JSON rendering
      block += `Full Avatar Profile:\n${JSON.stringify(profile, null, 2)}\n\n`;
    }
  }

  // Inject content themes with full detail rendering (including coreStress and content_engine_prompt context)
  if (user.contentThemes) {
    try {
      const themes =
        typeof user.contentThemes === "string"
          ? JSON.parse(user.contentThemes)
          : user.contentThemes;
      if (Array.isArray(themes) && themes.length > 0) {
        block += "Content Themes:\n";
        for (const t of themes) {
          if (typeof t === "string") {
            block += `  - ${t}\n`;
          } else {
            block += `  - ${t.name ?? t}`;
            if (t.coreStress) block += ` — "${t.coreStress}"`;
            block += "\n";
            if (t.content_engine_prompt) {
              block += `    Context: ${t.content_engine_prompt.slice(0, 200)}${t.content_engine_prompt.length > 200 ? "…" : ""}\n`;
            }
          }
        }
        block += "\n";
      }
    } catch {
      // ignore malformed JSON
    }
  }

  // Inject creator credentials so the AI can evaluate whether the script
  // uses the member's actual authority signals
  if (user.creatorCredentials?.trim()) {
    block += `Creator Credentials:\n${user.creatorCredentials.trim()}\n\n`;
  }

  block +=
    "Use ALL of the above avatar context to calibrate your feedback and rewrite. " +
    "The script must speak to the anxiety phases, internal monologue, and emotional triggers " +
    "described above — not to a generic audience.\n";

  return { block, name: user.avatarName ?? null };
}

export async function POST(req: NextRequest) {
  const user = await resolveUserFromSession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Change 3: Expanded DB select to include avatarProfile and creatorCredentials
  // Previously only fetched: avatarName, avatarSummary, contentThemes
  const dbUser = await prisma.user.findUnique({
    where: { id: user.id },
    select: {
      avatarName: true,
      avatarSummary: true,
      avatarProfile: true,
      contentThemes: true,
      creatorCredentials: true,
    },
  });

  const { videoTitle, scriptText, messages, conversationId } = await req.json();
  const isFirstCall = !conversationId && videoTitle && scriptText;

  const avatar = buildAvatarContext(dbUser ?? {});

  if (isFirstCall) {
    const systemPrompt = await getSystemPromptForMode(user.id, "analysis", avatar.block);

    const userMessage = `Video Title: ${videoTitle}\n\nScript:\n${scriptText}`;

    // Change 1 (model) + Change 2 (max_tokens): Fixed model string and increased tokens from 4000 to 8192
    // Higher token limit is required to support the new rewritten_script field in the JSON output
    const response = await claude.messages.create({
      model: MODEL,
      max_tokens: 8192,
      system: systemPrompt,
      messages: [{ role: "user", content: userMessage }],
    });

    const raw = response.content[0].type === "text" ? response.content[0].text : "";

    let analysis: any = null;
    try {
      const cleaned = raw.replace(/^```json?\s*/i, "").replace(/```\s*$/i, "").trim();
      analysis = JSON.parse(cleaned);
    } catch {
      return NextResponse.json(
        { error: "AI returned invalid JSON. Please try again.", raw },
        { status: 422 }
      );
    }

    const overallScore = analysis.overall_score ?? analysis.overallScore ?? null;

    const conversationMessages = [
      { role: "user", content: `**Video Title:** ${videoTitle}\n\n**Script:**\n${scriptText}`, hidden: true },
      {
        role: "assistant",
        content: analysis.one_sentence_diagnosis ?? "Script reviewed.",
        analysis,
        hidden: false,
      },
    ];

    const title = videoTitle.slice(0, 100);
    const conv = await prisma.aIToolConversation.create({
      data: {
        userId: user.id,
        toolType: "script_review",
        title,
        messages: conversationMessages as any,
        metadata: { overallScore, avatarName: avatar.name },
      },
    });

    return NextResponse.json({ analysis, conversationId: conv.id, overallScore });
  }

  if (!conversationId || !messages?.length) {
    return NextResponse.json({ error: "Missing conversationId or messages" }, { status: 400 });
  }

  const conversation = await prisma.aIToolConversation.findUnique({
    where: { id: conversationId },
  });
  if (!conversation) {
    return NextResponse.json({ error: "Conversation not found" }, { status: 404 });
  }
  if (conversation.userId !== user.id) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const systemPrompt = await getSystemPromptForMode(user.id, "chat", avatar.block);

  const contextMessages = Array.isArray(conversation.messages)
    ? (conversation.messages as any[])
        .filter((m) => !m.hidden)
        .map((m) => ({
          role: m.role as "user" | "assistant",
          content:
            m.role === "assistant" && m.analysis
              ? `[ANALYSIS SUMMARY] Score: ${(conversation.metadata as any)?.overallScore}/10. Diagnosis: ${m.analysis.one_sentence_diagnosis ?? ""}`
              : String(m.content),
        }))
    : [];

  const chatMessages = [
    ...contextMessages,
    ...messages.map((m: any) => ({
      role: m.role as "user" | "assistant",
      content: String(m.content),
    })),
  ];

  // Change 1 (model) + Change 2 (max_tokens): Applied to chat call as well
  const response = await claude.messages.create({
    model: MODEL,
    max_tokens: 8192,
    system: systemPrompt,
    messages: chatMessages,
  });

  const reply = response.content[0].type === "text" ? response.content[0].text : "";

  const savedMessages = Array.isArray(conversation.messages)
    ? [...(conversation.messages as any[])]
    : [];
  for (const m of messages) {
    savedMessages.push({ role: m.role, content: m.content, hidden: false });
  }
  savedMessages.push({ role: "assistant", content: reply, hidden: false });

  await prisma.aIToolConversation.update({
    where: { id: conversationId },
    data: { messages: savedMessages },
  });

  return NextResponse.json({ reply, conversationId });
}
