// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/content-planner-mobile/CalendarFirst.tsx": () => import("../components/mockups/content-planner-mobile/CalendarFirst.tsx"),
  "./components/mockups/content-planner-mobile/CardFeed.tsx": () => import("../components/mockups/content-planner-mobile/CardFeed.tsx"),
  "./components/mockups/content-planner-mobile/SwipeablePipeline.tsx": () => import("../components/mockups/content-planner-mobile/SwipeablePipeline.tsx")
};
